### PR TITLE
Remove Compass, don’t install platform-specific dependencies when not needed, fix instructions

### LINKED ISSUE #21: Missing support for Microsoft Windows OS for writers
Wrap tools in Docker container or add build instructions for MSW7 and MSW10 for tools.

### PR DESCRIPTION
**Pull request by jirutka**
This will also hopefully fix #21.

### CODE REVIEW

**Comment by bc-pavel-hubner** [comment]
This does not start on Ubuntu...

pavel@pavel-vmware-ubuntu:~/BigClown/bc-doc$ ./script/server 
== The Middleman is loading
/home/pavel/BigClown/bc-doc/.gem/bundler/gems/listen-4305d72f3f71/lib/listen/adapter/darwin.rb:25:in `require': cannot load such file -- rb-fsevent (LoadError)
	from /home/pavel/BigClown/bc-doc/.gem/bundler/gems/listen-4305d72f3f71/lib/listen/adapter/darwin.rb:25:in `usable?'
	from /home/pavel/BigClown/bc-doc/.gem/bundler/gems/listen-4305d72f3f71/lib/listen/adapter.rb:31:in `each'
	from /home/pavel/BigClown/bc-doc/.gem/bundler/gems/listen-4305d72f3f71/lib/listen/adapter.rb:31:in `detect'
	from /home/pavel/BigClown/bc-doc/.gem/bundler/gems/listen-4305d72f3f71/lib/listen/adapter.rb:31:in `_usable_adapter_class'
	from /home/pavel/BigClown/bc-doc/.gem/bundler/gems/listen-4305d72f3f71/lib/listen/adapter.rb:18:in `select'
	from /home/pavel/BigClown/bc-doc/.gem/bundler/gems/listen-4305d72f3f71/lib/listen/backend.rb:14:in `initialize'
	from /home/pavel/BigClown/bc-doc/.gem/bundler/gems/listen-4305d72f3f71/lib/listen/listener.rb:46:in `new'
	from /home/pavel/BigClown/bc-doc/.gem/bundler/gems/listen-4305d72f3f71/lib/listen/listener.rb:46:in `initialize'
	from /home/pavel/BigClown/bc-doc/.gem/bundler/gems/listen-4305d72f3f71/lib/listen.rb:36:in `new'
	from /home/pavel/BigClown/bc-doc/.gem/bundler/gems/listen-4305d72f3f71/lib/listen.rb:36:in `to'
	from /home/pavel/BigClown/bc-doc/.gem/gems/middleman-core-4.1.11/lib/middleman-core/sources/source_watcher.rb:176:in `listen!'
	from /home/pavel/BigClown/bc-doc/.gem/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /home/pavel/BigClown/bc-doc/.gem/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	from /home/pavel/BigClown/bc-doc/.gem/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /home/pavel/BigClown/bc-doc/.gem/gems/middleman-core-4.1.11/lib/middleman-core/sources.rb:249:in `each'
	from /home/pavel/BigClown/bc-doc/.gem/gems/middleman-core-4.1.11/lib/middleman-core/sources.rb:249:in `start!'
	from /home/pavel/BigClown/bc-doc/.gem/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /home/pavel/BigClown/bc-doc/.gem/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	from /home/pavel/BigClown/bc-doc/.gem/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /home/pavel/BigClown/bc-doc/.gem/gems/middleman-core-4.1.11/lib/middleman-core/core_extensions/file_watcher.rb:66:in `after_configuration'
	from /home/pavel/BigClown/bc-doc/.gem/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /home/pavel/BigClown/bc-doc/.gem/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	from /home/pavel/BigClown/bc-doc/.gem/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /home/pavel/BigClown/bc-doc/.gem/gems/middleman-core-4.1.11/lib/middleman-core/extension.rb:405:in `block in bind_after_configuration'
	from /home/pavel/BigClown/bc-doc/.gem/gems/middleman-core-4.1.11/lib/middleman-core/callback_manager.rb:57:in `instance_exec'
	from /home/pavel/BigClown/bc-doc/.gem/gems/middleman-core-4.1.11/lib/middleman-core/callback_manager.rb:57:in `block in execute'
	from /home/pavel/BigClown/bc-doc/.gem/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
	from /home/pavel/BigClown/bc-doc/.gem/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
	from /home/pavel/BigClown/bc-doc/.gem/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
	from /home/pavel/BigClown/bc-doc/.gem/gems/middleman-core-4.1.11/lib/middleman-core/callback_manager.rb:57:in `execute'
	from /home/pavel/BigClown/bc-doc/.gem/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /home/pavel/BigClown/bc-doc/.gem/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	from /home/pavel/BigClown/bc-doc/.gem/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /home/pavel/BigClown/bc-doc/.gem/gems/middleman-core-4.1.11/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'
	from /home/pavel/BigClown/bc-doc/.gem/gems/middleman-core-4.1.11/lib/middleman-core/application.rb:306:in `initialize'
	from /home/pavel/BigClown/bc-doc/.gem/gems/middleman-core-4.1.11/lib/middleman-core/preview_server.rb:144:in `new'
	from /home/pavel/BigClown/bc-doc/.gem/gems/middleman-core-4.1.11/lib/middleman-core/preview_server.rb:144:in `initialize_new_app'
	from /home/pavel/BigClown/bc-doc/.gem/gems/middleman-core-4.1.11/lib/middleman-core/preview_server.rb:34:in `start'
	from /home/pavel/BigClown/bc-doc/.gem/gems/middleman-cli-4.1.11/lib/middleman-cli/server.rb:53:in `server'
	from /home/pavel/BigClown/bc-doc/.gem/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/pavel/BigClown/bc-doc/.gem/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/pavel/BigClown/bc-doc/.gem/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /home/pavel/BigClown/bc-doc/.gem/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /home/pavel/BigClown/bc-doc/.gem/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /home/pavel/BigClown/bc-doc/.gem/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /home/pavel/BigClown/bc-doc/.gem/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /home/pavel/BigClown/bc-doc/.gem/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
	from /home/pavel/BigClown/bc-doc/.gem/gems/thor-0.19.1/lib/thor.rb:40:in `block in register'
	from /home/pavel/BigClown/bc-doc/.gem/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/pavel/BigClown/bc-doc/.gem/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/pavel/BigClown/bc-doc/.gem/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /home/pavel/BigClown/bc-doc/.gem/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/pavel/BigClown/bc-doc/.gem/gems/middleman-cli-4.1.11/bin/middleman:72:in `<top (required)>'
	from /home/pavel/BigClown/bc-doc/.gem/bin/middleman:23:in `load'
	from /home/pavel/BigClown/bc-doc/.gem/bin/middleman:23:in `<main>'

**Comment by jirutka** [comment]
This is bug in the listen gem. After the last change I’ve verified only that it correctly installs on Ubuntu, but not that it actually runs. Sorry for that. Please try it now, it should be fixed.

Note: Do _not_ merge it yet, I’ll rebase it after you finish the review.

**Comment by jirutka** [comment]
Well, on macOS it works since beginning, the problem was on Linux and Windows. ;) I’ll test it on Ubuntu once again now, but can’t test it on Windows.

**Comment by bc-pavel-hubner** [comment]
LOL, sorry my bad - of course I have tested it on Ubuntu (just under macOS and VMware :-)) ... getting dizzy this week ~.~

**Comment by jirutka** [comment]
@bc-pavel-hubner reported this build failure on Bash on Windows:

```
pavel@PHUBNER-PC-MAS:~/bc-doc$ lsb_release -aserver
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
pavel@PHUBNER-PC-MAS:~/bc-doc$

Bundle complete! 11 Gemfile dependencies, 42 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
/home/pavel/bc-doc/.gem/gems/middleman-livereload-3.4.6/lib/middleman-livereload/extension_3_1.rb:10:in `ip_address_list': Invalid argument - getifaddrs (Errno::EINVAL)
        from /home/pavel/bc-doc/.gem/gems/middleman-livereload-3.4.6/lib/middleman-livereload/extension_3_1.rb:10:in `<class:LiveReloadExtension>'
        from /home/pavel/bc-doc/.gem/gems/middleman-livereload-3.4.6/lib/middleman-livereload/extension_3_1.rb:5:in `<module:Middleman>'
        from /home/pavel/bc-doc/.gem/gems/middleman-livereload-3.4.6/lib/middleman-livereload/extension_3_1.rb:4:in `<top (required)>'
        from /home/pavel/bc-doc/.gem/gems/middleman-livereload-3.4.6/lib/middleman-livereload.rb:5:in `require'
        from /home/pavel/bc-doc/.gem/gems/middleman-livereload-3.4.6/lib/middleman-livereload.rb:5:in `block in <top (required)>'
        from /home/pavel/bc-doc/.gem/gems/middleman-core-4.1.11/lib/middleman-core/extensions.rb:91:in `load'
        from /home/pavel/bc-doc/.gem/gems/middleman-core-4.1.11/lib/middleman-core/extension_manager.rb:51:in `activate'
        from /home/pavel/bc-doc/config.rb:32:in `block in evaluate_configuration!'
        from /home/pavel/bc-doc/.gem/gems/middleman-core-4.1.11/lib/middleman-core/callback_manager.rb:57:in `instance_exec'
        from /home/pavel/bc-doc/.gem/gems/middleman-core-4.1.11/lib/middleman-core/callback_manager.rb:57:in `block in execute'
        from /home/pavel/bc-doc/.gem/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
        from /home/pavel/bc-doc/.gem/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
        from /home/pavel/bc-doc/.gem/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
        from /home/pavel/bc-doc/.gem/gems/middleman-core-4.1.11/lib/middleman-core/callback_manager.rb:57:in `execute'
        from /home/pavel/bc-doc/.gem/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
        from /home/pavel/bc-doc/.gem/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
        from /home/pavel/bc-doc/.gem/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from /home/pavel/bc-doc/.gem/gems/middleman-core-4.1.11/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'
        from /home/pavel/bc-doc/.gem/gems/middleman-core-4.1.11/lib/middleman-core/callback_manager.rb:58:in `instance_exec'
        from /home/pavel/bc-doc/.gem/gems/middleman-core-4.1.11/lib/middleman-core/callback_manager.rb:58:in `block in execute'
        from /home/pavel/bc-doc/.gem/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
        from /home/pavel/bc-doc/.gem/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
        from /home/pavel/bc-doc/.gem/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
        from /home/pavel/bc-doc/.gem/gems/middleman-core-4.1.11/lib/middleman-core/callback_manager.rb:58:in `execute'
        from /home/pavel/bc-doc/.gem/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
        from /home/pavel/bc-doc/.gem/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
        from /home/pavel/bc-doc/.gem/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from /home/pavel/bc-doc/.gem/gems/middleman-core-4.1.11/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'
        from /home/pavel/bc-doc/.gem/gems/middleman-core-4.1.11/lib/middleman-core/application.rb:289:in `initialize'
        from /home/pavel/bc-doc/.gem/gems/middleman-cli-4.1.11/bin/middleman:51:in `new'
        from /home/pavel/bc-doc/.gem/gems/middleman-cli-4.1.11/bin/middleman:51:in `<top (required)>'
        from /home/pavel/bc-doc/.gem/bin/middleman:23:in `load'
        from /home/pavel/bc-doc/.gem/bin/middleman:23:in `<main>'
```

It’s yet another problem of Windows Subsystem for Linux (WSL) and it does not affect only Ruby, but also many other programs. It’s reported in: https://github.com/Microsoft/BashOnWindows/issues/308.

In this case, it looks more like a missing feature in WSL than a bug (`getifaddrs` requires NETLINK\RAW socket support which is not implemented it). It may not be a problem if you compile Ruby directly on Windows, because Ruby can be compiled without `getifaddrs` (see source code [here](https://github.com/ruby/ruby/blob/4043565023531d173478c216e2a9cc6228f44a7e/ext/socket/socket.c#L1596))! So this is more a problem of using packages compiled for GNU/Linux on WSL, which is not and probably never can be **fully** compatible with Linux. MS should create their own repository or ask Canonical to add WSL as another target platform of Ubuntu (similar to HW architectures).

Could you please try to install Ruby on WSL using [rbenv](https://github.com/rbenv/rbenv) (and ruby-build)?

**Comment by jirutka** [comment]
@bc-pavel-hubner I’ve rebased this branch. If you don’t have any comments, I think that we can merge it. The mentioned problems on Windows are not caused by the changes proposed in this PR, so we can/should resolve them in a separate PR.

**Pull request merged**
